# Server
server.port=8080

# CXF
cxf.path=/
cxf.servlet.load-on-startup=1

# Log (gelistirme icin)
logging.level.org.apache.cxf=INFO
logging.level.com.onvif=DEBUG

# SOAP mesaj loglamasi (istege bagli)
cxf.feature.logging.enabled=true
cxf.feature.logging.in-memory-threshold=65536